# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Static Blog Generator
description: > # this means to ignore newlines until "baseurl:"
  Generate SEO Post Format For Github Pages. Support HexoJS and Jekyll
baseurl: "/static-blog-generator" # the subpath of your site, e.g. /blog
url: "https://www.webmanajemen.com" # the base hostname & protocol for your site

# Markdown settings
markdown: CommonMarkGhPages # kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# https://github.com/jekyll/jekyll-feed
feed:
  path: /atom.xml

# https://jekyllrb.com/docs/permalinks/
permalink: :title.html

# https://jekyllrb.com/docs/configuration/options/
timezone: Asia/Jakarta

# frontmatter
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
  - jekyll-feed # https://github.com/jekyll/jekyll-feed
  - jekyll-archives # https://github.com/jekyll/jekyll-archives

# https://github.com/github/jekyll-commonmark-ghpages#installation
# https://github.com/jekyll/jekyll-commonmark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "tables", "tagfilter"]
